name: docker

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-16-alpine}
    container_name: tech-haven-postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-tech-haven_db}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=C
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      docker_nginx_network:
        ipv4_address: 172.22.0.11
    restart: unless-stopped
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER:-postgres} -h localhost']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    container_name: tech-haven-app
    env_file:
      - ../.env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_NAME: ${DATABASE_NAME:-tech-haven_db}
      DATABASE_LOGGING: ${DATABASE_LOGGING:-false}
      JWT_SECRET: ${JWT_SECRET:-tech-haven-secret-key-dev}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-24h}
      APP_PORT: ${APP_PORT:-3000}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      PAYMENT_SERVICE_TYPE: ${PAYMENT_SERVICE_TYPE:-mock}
      TECH_HAVEN_SANDBOX_URL: ${TECH_HAVEN_SANDBOX_URL:-https://api-sandbox.co.uat.wompi.dev/v1}
      TECH_HAVEN_PUBLIC_KEY: ${TECH_HAVEN_PUBLIC_KEY:-pub_stagtest_g2u0HQd3ZMh05hsSgTS2lUV8t3s4mOt7}
      TECH_HAVEN_PRIVATE_KEY: ${TECH_HAVEN_PRIVATE_KEY:-prv_stagtest_5i0ZGIGiFcDQifYsXxvsny7Y37tKqFWg}
      TECH_HAVEN_EVENTS_KEY: ${TECH_HAVEN_EVENTS_KEY:-stagtest_events_2PDUmhMywUkvb1LvxYnayFbmofT7w39N}
      TECH_HAVEN_INTEGRITY_KEY: ${TECH_HAVEN_INTEGRITY_KEY:-stagtest_integrity_nAIBuqayW70XpUqJS4qf4STYiISd89Fp}
      DB_STARTUP_DELAY: ${DB_STARTUP_DELAY:-60}
    command: sh -c "echo 'Waiting ${DB_STARTUP_DELAY} seconds for the database to start...' && sleep ${DB_STARTUP_DELAY} && echo 'Starting the application...' && node dist/main.js"
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      docker_nginx_network:
        ipv4_address: 172.22.0.13
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:3000/api/docs',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  docker_nginx_network:
    external: true
