version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: wompi-postgres
    environment:
      POSTGRES_DB: wompi_db
      POSTGRES_USER: wompi_user
      POSTGRES_PASSWORD: wompi_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      wompi_network:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: wompi-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wompi.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      wompi_network:
        ipv4_address: 172.20.0.11
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  wompi_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
