version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: tech-haven-postgres
    environment:
      POSTGRES_DB: tech-haven_db
      POSTGRES_USER: tech-haven_user
      POSTGRES_PASSWORD: tech-haven_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      tech-haven_network:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: tech-haven-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tech-haven.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      tech-haven_network:
        ipv4_address: 172.20.0.11
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  tech-haven_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
